### ISSUE TITLE
Should I rename The project name?

### ISSUE THREAD

**Issue by honestly-nuts** [honestly-nuts/Scuffed-Utils#22]
I've been thinking about the name. When I named the project I thought it was funny and quirky but now it just seems a little amateurish. And now I'm in a dilemma: should I rename the project or not. And I'm usually known for making bad decision (like using that old weird looking icon), so I want your suggestions. what do you recken'? and what name should you think this project should be named? I recken' something like modular-utils or Nutils (like ncurses). Please comment below.

**Comment by Soumyak100** [comment]
Suggestions:
1. **scf-utils** (Simillar to Scuffed-Utils)
2. **pgc-utils** (Python GNU Core Utils)

and **Nutils** is also okay.

**Comment by honestly-nuts** [comment]
I do like your suggestions. I also suggest
  1. Py-utils (python-utils)
  2. PCU (python core utils)
