### ISSUE TITLE
Cat should print immediately

### ISSUE THREAD

**Issue by cpebble** [honestly-nuts/Scuffed-Utils#6]
When using scat, you read everything into a buffer, then write it all out at the end. This is unwanted behavior for two reasons:  
1. You might cat a neverending file such as /dev/null or a socket. Cat should just read the bytes and print them out to stdout.  
2. You might run into oom errors on large files. 

Refer to https://github.com/coreutils/coreutils/blob/master/src/cat.c for the original implementation and to `scat.py` for the implementation in question

**Comment by honestly-nuts** [comment]
Your issue is valid and reasonable but I want all of the modules to be used by other programs and printing it out directly can make it inflexible. But you also have valid points so I'll think about it.

**Comment by mrcpj1998** [comment]
Then you should wrap your call to print so you can handle either running as a command or as a module. 

You also need error handling if write or read errors, and in your newest revision of scat you need to detect EOF from stdin
